### Data Cleaning

In [7]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent   # because notebook is inside /code
sys.path.append(str(PROJECT_ROOT))

In [8]:
from src.data_preprocessing import preprocess_data

df = preprocess_data("../data/Personal_Finance_Dataset.csv")
df.head()

        date      category   amount     type  signed_amount
0 2020-01-02  Food & Drink  1485.69  Expense       -1485.69
1 2020-01-02     Utilities  1475.58  Expense       -1475.58
2 2020-01-04          Rent  1185.08  Expense       -1185.08
3 2020-01-05    Investment  2291.00   Income        2291.00
4 2020-01-13  Food & Drink  1126.88  Expense       -1126.88

### Monthly Spending (Feature Engineering)

In [9]:
from src.monthly_spending import save_monthly_spending_table

monthly_table = save_monthly_spending_table(df, "../data/monthly_spending_table.csv")
monthly_table.head()

category,month,Entertainment,Food & Drink,Health & Fitness,Rent,Salary,Shopping,Travel,Utilities
0,2020-01,1914.85,5458.51,2370.34,3663.22,1077.09,1178.66,0.00,1475.58
1,2020-02,3199.52,1829.57,766.81,1222.17,294.31,1499.79,7272.28,1023.96
2,2020-03,1887.05,1353.18,881.82,6241.21,0.00,1929.08,486.51,802.96
3,2020-04,3821.84,1938.30,1603.18,0.00,2222.60,388.92,3195.04,3063.17
4,2020-05,0.00,2501.62,2893.98,3822.55,318.05,1318.17,4288.25,1703.51

In [10]:
from src.trends import calculate_trends_and_volatility

# Add the behavioral trend features
final_behavioral_df = calculate_trends_and_volatility(monthly_table)

# View the results
final_behavioral_df[['month', 'total_expense', 'rolling_3m_expense', 'spending_volatility']].head()

category    month  total_expense  rolling_3m_expense  spending_volatility
0         2020-01       17138.25                 NaN                  NaN
1         2020-02       17108.41                 NaN                  NaN
2         2020-03       13581.81        15942.823333             0.128255
3         2020-04       16233.05        15641.090000             0.117403
4         2020-05       16846.13        15553.663333             0.111547